name: Docker Image CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Login step only executed for pushes to main
      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_Token }}

      # Build and tag the production Docker image
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ghcr.io/alonsoernesto/ecommerce-express:${{ github.sha }}
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
            docker tag ghcr.io/alonsoernesto/ecommerce-express:${{ github.sha }} ghcr.io/alonsoernesto/ecommerce-express:latest
          fi

      # Push the production Docker image
      - name: Push the Docker image
        if: github.ref == 'refs/heads/master'
        run: |
          docker push ghcr.io/alonsoernesto/ecommerce-express:${{ github.sha }}
          docker push ghcr.io/alonsoernesto/ecommerce-express:latest
          # docker push ghcr.io/${{ github.repository }}:latest
